# ---- Global Settings ----
enable-magisk-update = false
parallel-jobs = 4
compression-level = 9
remove-rv-integrations-checks = true
rebuild-all-on-update = false
riplib = true
build-mode = "apk"
arch = "arm64-v8a"

jvm-flags = "-Dfile.encoding=utf-8 -Djdk.util.zip.disableZip64ExtraFieldValidation=true -Djdk.nio.zipfs.allowDotZipEntry=true -Xmx2G -XX:+UseParallelGC -XX:+UseStringDeduplication"

optimize-apk = true
optimize-languages = "en"
optimize-densities = "nodpi,anydpi,xxhdpi"
zipalign = true
cache-apk = true

patches-version = "dev"
cli-version = "dev"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "RVX"

# ---- Patch Sources (nested table syntax) ----
[PatchSources.rvx]
source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
version = "dev"
cli-version = "dev"

[PatchSources.privacy]
source = "jkennethcarino/privacy-revanced-patches"
cli-source = "ReVanced/revanced-cli"
version = "latest"
cli-version = "latest"

# ---- Apps ----
[YouTube]
enabled = true
version = "20.21.37"
arch = "arm64-v8a"
riplib = true
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
patch-sources = "privacy,rvx"
#included-patches = "'Change version code'"
excluded-patches = "'Alternative thumbnails' 'Enable gradient loading screen' 'Enable debug logging'"
#patcher-args = "-e 'Custom branding icon for YouTube' -OappIcon=mmt -OdarkThemeBackgroundColor=@android:color/black -OlightThemeBackgroundColor=@android:color/white -OstrokeColor=?attr/ytChipBackground -e 'Visual preferences icons for YouTube' -OsettingsMenuIcon=revanced"
optimize-apk = true
optimize-languages = "en"
optimize-densities = "nodpi,xxhdpi,xxxhdpi"

[Music]
enabled = true
version = "8.30.54"
arch = "arm64-v8a"
riplib = true
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
patch-sources = "privacy,rvx"
#included-patches = "'Change version code' 'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'Disable music video in album'"
excluded-patches = "'Enable debug logging'"
#patcher-args = "-e 'Custom branding icon for YouTube Music' -OappIcon=mmt -e 'Visual preferences icons for YouTube Music' -OsettingsMenuIcon=revanced"
optimize-apk = true
optimize-languages = "en"

[Reddit]
enabled = true
app-name = "Reddit"
arch = "arm64-v8a"
dpi = "320-480dpi"
version = "auto"
riplib = true
#included-patches = "'Change version code' 'Custom branding name for Reddit'"
#patcher-args = "-e 'Custom branding name for Reddit' -OappName='RVX Reddit'"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"

[Spotify]
enabled = true
app-name = "Spotify"
arch = "arm64-v8a"
version = "auto"
riplib = true
#included-patches = "'Change version code' 'Custom theme'"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
#patcher-args = "-e 'Custom branding name for Spotify' -OappName='RVX Spotify'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/spotify-ab/spotify-music-podcasts"

[TikTok]
enabled = false
arch = "arm64-v8a"
included-patches = "'SIM spoof'"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly"

[X]
enabled = false
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
patches-source = "crimera/piko"
rv-brand = "Piko"
included-patches = "'Change version code' 'Dynamic color'"
dpi = "120-640dpi"
