enable-magisk-update = false
parallel-jobs = 1
compression-level = 9
remove-rv-integrations-checks = true
rebuild-all-on-update = false

patches-version = "dev"
cli-version = "dev"

# TODO: organising

[YouTube]
enabled = true
build-mode = "apk"
version = "20.21.37"
arch = "arm64-v8a"
riplib = true
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
included-patches = "'Change version code' 'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'MaterialYou' 'Theme' 'Custom header for YouTube'"
excluded-patches = "'Alternative thumbnails' 'Enable gradient loading screen' 'Enable debug logging'"
patcher-args = "-e 'Custom branding icon for YouTube' -OappIcon='revancify_red' -OdarkThemeBackgroundColor=@android:color/black -OlightThemeBackgroundColor=@android:color/white -OstrokeColor=?attr/ytChipBackground -e 'Visual preferences icons for YouTube' -OsettingsMenuIcon=revanced"
#patcher-args = "--legacy-options=options.json"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "RVX"
# Todo:
# apkmirror-dpi = "480dpi"
# experimental, highhly depends on release. Probably not usable

[Music]
enabled = true
build-mode = "apk"
version = "8.30.54"
arch = "arm64-v8a"
riplib = true
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
included-patches = "'Change version code' 'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'Disable music video in album'"
excluded-patches = "'Enable debug logging'"
patcher-args = "-e 'Custom branding icon for YouTube Music' -OappIcon='revancify_red' -e 'Visual preferences icons for YouTube Music' -OsettingsMenuIcon=revanced"
#patcher-args = "--legacy-options=options.json"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "RVX"

[Reddit]
enabled = false
app-name = "Reddit"
build-mode = "apk"
arch = "arm64-v8a"
apkmirror-dpi = "320-480dpi" # slightly smaller size
version = "auto"
riplib = true
included-patches = "'Change version code' 'Custom branding name for Reddit'"
patcher-args = "-e 'Custom branding name for Reddit' -OappName='RVX Reddit'"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "RVX"

[Spotify]
enabled = false
app-name = "Spotify"
build-mode = "apk"
arch = "arm64-v8a"
version = "auto"
riplib = true
included-patches = "'Change version code' 'Custom theme'"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
patcher-args = "-e 'Custom branding name for Spotify' -OappName='RVX Spotify'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/spotify-ab/spotify-music-podcasts"

[Twitter]
enabled = false
build-mode = "apk"
apkmirror-dpi = "120-640dpi"
# TODO: ensure dpi is correct
#dpi = "120-640dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"

[TikTok]
enabled = false
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
included-patches = "'SIM spoof'"

