enable-magisk-update = true
parallel-jobs = 1
compression-level = 9

[YouTube]
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
included-patches = "'MaterialYou' 'Return YouTube Username'"
patcher-args = "--legacy-options=options.json"
build-mode = "both"

[Music]
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
included-patches = "'Disable music video in album' 'Return YouTube Username'"
patcher-args = "--legacy-options=options.json"
build-mode = "both"
arch = "both"

[Reddit]
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
apkmirror-dpi = "120-640dpi"

[Telegram]
apkmirror-dlurl = "https://www.apkmirror.com/apk/telegram-fz-llc/telegram"
uptodown-dlurl = "https://telegram.en.uptodown.com/android"
patches-source = "Aunali321/ReVancedExperiments"
rv-brand = "ReVanced Experiments"

[Instagram]
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
patches-source = "Aunali321/ReVancedExperiments"
rv-brand = "ReVanced Experiments"
arch = "both"